[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "ctower"
version = "0.1.0"
description = ""
authors = ["Tony"]

[tool.poetry.dependencies]
python = "^3.9"
playsound = "1.3.0"
